# Generated by Django 5.1.1 on 2024-12-01 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
